config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'

  get 'user/display/:id', to: 'user#display'

  get 'potin/:id', to: 'potin#content'

  get '/welcome/:id', to: 'welcome#first_name'

  get '/team', to: 'static#team'
  
  get '/contact', to: 'static#contact'

  resources :gossips, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name,
    presence: true
  validates :zip_code,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..40 }
  validates :content,
    presence: true,
    length: { in: 1..140 }
  validates :user_id,
    presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name,
    presence: true
  validates :last_name,
    presence: true
  validates :description,
    presence: true,
    length: { in: 1..140 }
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :city_id,
    presence: true
  validates :age,
    presence: true
  belongs_to :city
  has_many :gossips

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: rand(1..10))
    if @gossip.save
      flash[:notice] = "Ton gossip a bien été créé !"
      redirect_to root_path
      return
    else 
      render :new
    end
  end

  def show
  end

end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @gossip = Gossip.all
    @user = User.all
  end
end

app/controllers/potin_controller.rb
class PotinController < ApplicationController
  def content
    @potin = Gossip.find(params[:id])
    p @potin.id
    @user = User.all
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def display
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def first_name
    @user = User.find(params[:id])
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts params[:id]
    puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/potin_helper.rb
module PotinHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
<div class="alert alert-danger text-center" role="alert">
  Tu as mal rampli le formulaire. Réessaye !
</div>
<% else %>
<% end %>

<div class="container">
<h1 class="pt-5"> Crée ton Gossip!</h1>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="form-group">
      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title, class: 'form-control',  placeholder: "ex : Jenna aime les chibres" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossip.content, class: 'form-control', placeholder: "ex : Elle en mange 6 fois par jour" %>
    </div>

      <%= submit_tag "Create Post", class: 'btn btn-default btn-dark text-light btn-submit' %>
    <% end %>
</div>

app/views/home_page/index.html.erb
<div class="container pt-5">
  <h1>Bienvenue sur The Gossip Project !</h1>
  <p>Voici la liste de nos derniers gossips</p>
  <div class="row pt-4">
    <table class="table">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Auteur</th>
          <th scope="col">Titre</th>
          <th scope="col">Gossip</th>
          <th scope="col">Voir le potin</th>
        </tr>
      </thead>
      <tbody>
        <% @gossip.each_with_index do |gossip, i| %>
          <tr>
            <th scope="row"><%= gossip.id %></th>
            <td><%= @user.find(gossip.user_id).full_name %></td>
            <td><%= gossip.title %></td>
            <td><%= gossip.content %></td>
            <td><a href="/potin/<%= gossip.id %>" target='_blank'>Voir</a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" <%= link_to "The Gossip Project", root_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"<%= link_to "Home", root_path %>
      </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to "L'équipe", team_path %>
      </li>
      <li class="nav-item">
      <a class="nav-link"<%= link_to "Contact", contact_path %>
      </li>
    </ul>
    <span class="nav-item">
      <a class="nav-link text-light" <%= link_to "Créer un Gossip !", new_gossip_path %>
    </span>
  </div>
</nav>
    <% flash.each do |name, msg| %>
      <div class="alert alert-success text-center">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
    <!-- Footer -->
<footer class="page-footer font-small bg-dark text-white fixed-bottom">
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright: Segrelove Inc
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
    
  </body>
</html>

app/views/potin/content.html.erb
<div class="card text-center text-white bg-dark mb-3 mx-auto mt-5" style="width: 400px;">
    <div class="card-header "><%= @user.find(@potin.user_id).full_name %></div>
      <div class="card-body">
    <h5 class="card-title"><%= @potin.title %></h5>
    <p><i><%= @potin.content %></i></p>
    <a href="/user/display/<%= @user.find(@potin.user_id).id%>" class="btn btn-light">Voir l'auteur</a>
  </div>
</div>

app/views/user/display.html.erb
<div class="card text-center text-white bg-dark mb-3 mx-auto mt-5" style="width: 400px;">
    <div class="card-header "><%= @user.full_name %></div>
      <div class="card-body">
    <h5 class="card-title"><%= @user.description %></h5>
    <p><i><%= @user.age %> ans</i><br/>
          <%= @user.email %>
    </p>
    <a  class="btn btn-light" <%= link_to "Retour à l'accueil", root_path %></a>
  </div>
</div>

app/views/welcome/first_name.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>BIENVENUE <%= @user.first_name %> !</h1>
      <p>Ici c'est notre super site de potins, il est chouette, non ?</p>
    </div>
  </div>
</div>